apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u7p8kz4el-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u7p8kz4el-nodejs 
  name: u7p8kz4el-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: u7p8kz4el-nodejs 
